"""empty message

Revision ID: 235833018e75
Revises: 0c2f083d1621
Create Date: 2019-07-24 16:19:01.906585

"""

# revision identifiers, used by Alembic.
revision = '235833018e75'
down_revision = '0c2f083d1621'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('academic_degree', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('account_receivable', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('address_2', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('bank_account_mandate_reference', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('bank_account_number', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('bank_account_owner', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('bank_bic', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('bank_code', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('bank_iban', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('bank_name', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('city', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('country_code', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('created_on_fb', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('currency_code', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('customer_id', sa.String(length=250), nullable=True))
    op.add_column('customer', sa.Column('customer_number', sa.String(length=250), nullable=True))
    op.add_column('customer', sa.Column('customer_type', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('days_for_payment', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('fax', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('first_name', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('last_name', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('mobile', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('newsletter_optin', sa.Boolean(), nullable=True))
    op.add_column('customer', sa.Column('organization', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('payment_type', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('phone', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('phone_2', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('position', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('salutation', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('secondary_address', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('show_payment_notice', sa.Boolean(), nullable=True))
    op.add_column('customer', sa.Column('tags', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('top', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('vat_id', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('customer', sa.Column('zipcode', sa.String(length=200), nullable=True))
    op.alter_column('customer', 'title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_customer_customer_id'), 'customer', ['customer_id'])
    op.create_unique_constraint(op.f('uq_customer_customer_number'), 'customer', ['customer_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_customer_customer_number'), 'customer', type_='unique')
    op.drop_constraint(op.f('uq_customer_customer_id'), 'customer', type_='unique')
    op.alter_column('customer', 'title',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('customer', 'zipcode')
    op.drop_column('customer', 'website')
    op.drop_column('customer', 'vat_id')
    op.drop_column('customer', 'top')
    op.drop_column('customer', 'tags')
    op.drop_column('customer', 'show_payment_notice')
    op.drop_column('customer', 'secondary_address')
    op.drop_column('customer', 'salutation')
    op.drop_column('customer', 'position')
    op.drop_column('customer', 'phone_2')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'payment_type')
    op.drop_column('customer', 'organization')
    op.drop_column('customer', 'newsletter_optin')
    op.drop_column('customer', 'mobile')
    op.drop_column('customer', 'last_name')
    op.drop_column('customer', 'first_name')
    op.drop_column('customer', 'fax')
    op.drop_column('customer', 'email')
    op.drop_column('customer', 'days_for_payment')
    op.drop_column('customer', 'customer_type')
    op.drop_column('customer', 'customer_number')
    op.drop_column('customer', 'customer_id')
    op.drop_column('customer', 'currency_code')
    op.drop_column('customer', 'created_on_fb')
    op.drop_column('customer', 'country_code')
    op.drop_column('customer', 'city')
    op.drop_column('customer', 'bank_name')
    op.drop_column('customer', 'bank_iban')
    op.drop_column('customer', 'bank_code')
    op.drop_column('customer', 'bank_bic')
    op.drop_column('customer', 'bank_account_owner')
    op.drop_column('customer', 'bank_account_number')
    op.drop_column('customer', 'bank_account_mandate_reference')
    op.drop_column('customer', 'address_2')
    op.drop_column('customer', 'address')
    op.drop_column('customer', 'account_receivable')
    op.drop_column('customer', 'academic_degree')
    # ### end Alembic commands ###
