"""empty message

Revision ID: 7589170f90c6
Revises: 82184d7d1e88
Create Date: 2019-07-23 17:05:45.258565

"""

# revision identifiers, used by Alembic.
revision = '7589170f90c6'
down_revision = '82184d7d1e88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_team_member_team_id'), 'team_member', ['team_id', 'user_id'])
    op.drop_constraint('_team_user_uc', 'team_member', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_team_user_uc', 'team_member', ['team_id', 'user_id'])
    op.drop_constraint(op.f('uq_team_member_team_id'), 'team_member', type_='unique')
    # ### end Alembic commands ###
